version: '3.8'

services:
  # Backend Service (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: polaris_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Service (React/Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: polaris_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: npm run dev
    stdin_open: true
    tty: true

volumes:
  node_modules:
