version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: polaris_backend
    ports:
      - "8000:8000"
    volumes: 
      - ./backend:/app
      - ./backend/serviceAccountKey.json:/app/serviceAccountKey.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: polaris_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: