# config.yaml
workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: 'us-central1-docker.pkg.dev/your-project-id/job-rec-repo/training-pipeline:latest'
      env:
        - name: GCS_BUCKET
          value: 'job-rec-pipeline-artifacts'